// ─── Location types ───────────────────────────────────────────────────────────

export interface StateItem {
  id: number;
  name: string;
}

export interface CourtItem {
  id: number;
  name: string;
  stateId: number;
}

// ─── Static fallback data (used when API is unavailable) ─────────────────────
// IDs here match what the backend seeds; the API is the source of truth.

export const STATIC_STATES: StateItem[] = [
  { id: 1,  name: "Andhra Pradesh" },
  { id: 2,  name: "Arunachal Pradesh" },
  { id: 3,  name: "Assam" },
  { id: 4,  name: "Bihar" },
  { id: 5,  name: "Chhattisgarh" },
  { id: 6,  name: "Goa" },
  { id: 7,  name: "Gujarat" },
  { id: 8,  name: "Haryana" },
  { id: 9,  name: "Himachal Pradesh" },
  { id: 10, name: "Jharkhand" },
  { id: 11, name: "Karnataka" },
  { id: 12, name: "Kerala" },
  { id: 13, name: "Madhya Pradesh" },
  { id: 14, name: "Maharashtra" },
  { id: 15, name: "Manipur" },
  { id: 16, name: "Meghalaya" },
  { id: 17, name: "Mizoram" },
  { id: 18, name: "Nagaland" },
  { id: 19, name: "Odisha" },
  { id: 20, name: "Punjab" },
  { id: 21, name: "Rajasthan" },
  { id: 22, name: "Sikkim" },
  { id: 23, name: "Tamil Nadu" },
  { id: 24, name: "Telangana" },
  { id: 25, name: "Tripura" },
  { id: 26, name: "Uttar Pradesh" },
  { id: 27, name: "Uttarakhand" },
  { id: 28, name: "West Bengal" },
  { id: 29, name: "Delhi" },
  { id: 30, name: "Jammu & Kashmir" },
  { id: 31, name: "Ladakh" },
  { id: 32, name: "Puducherry" },
  { id: 33, name: "Chandigarh" },
  { id: 34, name: "Andaman & Nicobar Islands" },
  { id: 35, name: "Dadra & Nagar Haveli" },
  { id: 36, name: "Daman & Diu" },
  { id: 37, name: "Lakshadweep" },
];


export const STATIC_DISTRICTS: DistrictItem[] = [
  { id: 1, value: 'AP-01', name: "Andhra Pradesh", stateId: 1 },
  { id: 2, value: 'AP-01', name: "Arunachal Pradesh", stateId: 2 },
  { id: 3, value: 'AP-01', name: "Assam", stateId: 3 },
  { id: 4, value: 'AP-01', name: "Bihar", stateId: 4 },
  { id: 5, value: 'AP-01', name: "Chhattisgarh", stateId: 5 },
  { id: 6, value: 'AP-01', name: "Goa", stateId: 6 },
  { id: 7, value: 'AP-01', name: "Gujarat", stateId: 7 },
  { id: 8, value: 'AP-01', name: "Haryana", stateId: 8 },
  { id: 9, value: 'AP-01', name: "Himachal Pradesh", stateId: 9 },
  { id: 10,value: 'AP-01', name: "Jharkhand", stateId: 10 },
  { id: 11,value: 'AP-01', name: "Karnataka", stateId: 11 },

  { id: 1201, value: 'KL-01', name: 'Thiruvananthapuram', stateId: 12 },
  { id: 1202, value: 'KL-02', name: 'Kollam', stateId: 12 },
  { id: 1203, value: 'KL-03', name: 'Pathanamthitta', stateId: 12 },
  { id: 1204, value: 'KL-04', name: 'Alappuzha', stateId: 12 },
  { id: 1205, value: 'KL-05', name: 'Kottayam', stateId: 12 },
  { id: 1206, value: 'KL-06', name: 'Idukki', stateId: 12 },
  { id: 1207, value: 'KL-07', name: 'Ernakulam', stateId: 12 },
  { id: 1208, value: 'KL-08', name: 'Thrissur', stateId: 12 },
  { id: 1209, value: 'KL-09', name: 'Palakkad', stateId: 12 },
  { id: 1210, value: 'KL-10', name: 'Malappuram', stateId: 12 },
  { id: 1211, value: 'KL-11', name: 'Kozhikode', stateId: 12 },
  { id: 1212, value: 'KL-12', name: 'Wayanad', stateId: 12 },
  { id: 1213, value: 'KL-13', name: 'Kannur', stateId: 12 },


  { id: 13, value: '1234', name: "Madhya Pradesh", stateId: 13 },
  { id: 14, value: '1234', name: "Maharashtra", stateId: 14 },
  { id: 15, value: '1234', name: "Manipur", stateId: 15 },
  { id: 16, value: '1234', name: "Meghalaya", stateId: 16 },
  { id: 17, value: '1234', name: "Mizoram", stateId: 17 },
  { id: 18, value: '1234', name: "Nagaland", stateId: 18 },
  { id: 19, value: '1234', name: "Odisha", stateId: 19 },
  { id: 20, value: '1234', name: "Punjab", stateId: 20 },
  { id: 21, value: '1234', name: "Rajasthan", stateId: 21 },
  { id: 22, value: '1234', name: "Sikkim", stateId: 22 },
  { id: 23, value: '1234', name: "Tamil Nadu", stateId: 23 },
  { id: 24, value: '1234', name: "Telangana", stateId: 24 },
  { id: 25, value: '1234', name: "Tripura", stateId: 25 },
  { id: 26, value: '1234', name: "Uttar Pradesh", stateId: 26 },
  { id: 27, value: '1234', name: "Uttarakhand", stateId: 27 },
  { id: 28, value: '1234', name: "West Bengal", stateId: 28 },
  { id: 29, value: '1234', name: "Delhi", stateId: 29 },
  { id: 30, value: '1234', name: "Jammu & Kashmir", stateId: 30 },
  { id: 31, value: '1234', name: "Ladakh", stateId: 31 },
  { id: 32, value: '1234', name: "Puducherry", stateId: 32 },
  { id: 33, value: '1234', name: "Chandigarh", stateId: 33 },
  { id: 34, value: '1234', name: "Andaman & Nicobar Islands", stateId: 34 },
  { id: 35, value: '1234', name: "Dadra & Nagar Haveli", stateId: 35 },
  { id: 36, value: '1234', name: "Daman & Diu", stateId: 36 },
  { id: 37, value: '1234', name: "Lakshadweep", stateId: 37 },
];

export const STATIC_COURTS: CourtItem[] = [
  // Andhra Pradesh (1)
  { id: 1001, stateId: 1,  name: "Andhra Pradesh High Court" },
  { id: 1002, stateId: 1,  name: "City Civil Court, Visakhapatnam" },
  { id: 1003, stateId: 1,  name: "District Court, Vijayawada" },
  { id: 1004, stateId: 1,  name: "District Court, Guntur" },
  { id: 1005, stateId: 1,  name: "District Court, Tirupati" },
  { id: 1006, stateId: 1,  name: "Family Court, Visakhapatnam" },
  { id: 1007, stateId: 1,  name: "Labour Court, Vijayawada" },
  { id: 1008, stateId: 1,  name: "Consumer Disputes Redressal Commission, Andhra Pradesh" },
  // Assam (3)
  { id: 3001, stateId: 3,  name: "Gauhati High Court" },
  { id: 3002, stateId: 3,  name: "District Court, Guwahati" },
  { id: 3003, stateId: 3,  name: "Family Court, Guwahati" },
  { id: 3004, stateId: 3,  name: "Consumer Disputes Redressal Commission, Assam" },
  // Bihar (4)
  { id: 4001, stateId: 4,  name: "Patna High Court" },
  { id: 4002, stateId: 4,  name: "District Court, Patna" },
  { id: 4003, stateId: 4,  name: "District Court, Muzaffarpur" },
  { id: 4004, stateId: 4,  name: "District Court, Gaya" },
  { id: 4005, stateId: 4,  name: "Family Court, Patna" },
  { id: 4006, stateId: 4,  name: "Consumer Disputes Redressal Commission, Bihar" },
  // Chhattisgarh (5)
  { id: 5001, stateId: 5,  name: "Chhattisgarh High Court" },
  { id: 5002, stateId: 5,  name: "District Court, Raipur" },
  { id: 5003, stateId: 5,  name: "District Court, Bilaspur" },
  { id: 5004, stateId: 5,  name: "Family Court, Raipur" },
  { id: 5005, stateId: 5,  name: "Consumer Disputes Redressal Commission, Chhattisgarh" },
  // Goa (6)
  { id: 6001, stateId: 6,  name: "Bombay High Court (Goa Bench)" },
  { id: 6002, stateId: 6,  name: "District Court, Panaji" },
  { id: 6003, stateId: 6,  name: "District Court, Margao" },
  { id: 6004, stateId: 6,  name: "Family Court, Panaji" },
  { id: 6005, stateId: 6,  name: "Consumer Disputes Redressal Commission, Goa" },
  // Gujarat (7)
  { id: 7001, stateId: 7,  name: "Gujarat High Court" },
  { id: 7002, stateId: 7,  name: "City Civil Court, Ahmedabad" },
  { id: 7003, stateId: 7,  name: "District Court, Surat" },
  { id: 7004, stateId: 7,  name: "District Court, Vadodara" },
  { id: 7005, stateId: 7,  name: "District Court, Rajkot" },
  { id: 7006, stateId: 7,  name: "Family Court, Ahmedabad" },
  { id: 7007, stateId: 7,  name: "Labour Court, Ahmedabad" },
  { id: 7008, stateId: 7,  name: "Consumer Disputes Redressal Commission, Gujarat" },
  { id: 7009, stateId: 7,  name: "Debt Recovery Tribunal, Ahmedabad" },
  // Haryana (8)
  { id: 8001, stateId: 8,  name: "Punjab & Haryana High Court" },
  { id: 8002, stateId: 8,  name: "District Court, Faridabad" },
  { id: 8003, stateId: 8,  name: "District Court, Gurugram" },
  { id: 8004, stateId: 8,  name: "District Court, Ambala" },
  { id: 8005, stateId: 8,  name: "District Court, Hisar" },
  { id: 8006, stateId: 8,  name: "Family Court, Faridabad" },
  { id: 8007, stateId: 8,  name: "Consumer Disputes Redressal Commission, Haryana" },
  // Himachal Pradesh (9)
  { id: 9001, stateId: 9,  name: "Himachal Pradesh High Court" },
  { id: 9002, stateId: 9,  name: "District Court, Shimla" },
  { id: 9003, stateId: 9,  name: "District Court, Dharamshala" },
  { id: 9004, stateId: 9,  name: "District Court, Mandi" },
  { id: 9005, stateId: 9,  name: "Family Court, Shimla" },
  { id: 9006, stateId: 9,  name: "Consumer Disputes Redressal Commission, Himachal Pradesh" },
  // Jharkhand (10)
  { id: 10001, stateId: 10, name: "Jharkhand High Court" },
  { id: 10002, stateId: 10, name: "District Court, Ranchi" },
  { id: 10003, stateId: 10, name: "District Court, Jamshedpur" },
  { id: 10004, stateId: 10, name: "District Court, Dhanbad" },
  { id: 10005, stateId: 10, name: "Family Court, Ranchi" },
  { id: 10006, stateId: 10, name: "Consumer Disputes Redressal Commission, Jharkhand" },
  // Karnataka (11)
  { id: 11001, stateId: 11, name: "Karnataka High Court" },
  { id: 11002, stateId: 11, name: "Dharwad Bench of Karnataka High Court" },
  { id: 11003, stateId: 11, name: "Kalaburagi Bench of Karnataka High Court" },
  { id: 11004, stateId: 11, name: "City Civil Court, Bengaluru" },
  { id: 11005, stateId: 11, name: "District Court, Mysuru" },
  { id: 11006, stateId: 11, name: "District Court, Hubli-Dharwad" },
  { id: 11007, stateId: 11, name: "District Court, Mangaluru" },
  { id: 11008, stateId: 11, name: "District Court, Belagavi" },
  { id: 11009, stateId: 11, name: "Family Court, Bengaluru" },
  { id: 11010, stateId: 11, name: "Labour Court, Bengaluru" },
  { id: 11011, stateId: 11, name: "Consumer Disputes Redressal Commission, Karnataka" },
  { id: 11012, stateId: 11, name: "National Company Law Tribunal, Bengaluru" },
  // Kerala (12)
  { id: 12001, stateId: 12, name: "Kerala High Court" },
  { id: 12002, stateId: 12, name: "City Civil Court, Ernakulam" },
  { id: 12003, stateId: 12, name: "District Court, Thiruvananthapuram" },
  { id: 12004, stateId: 12, name: "District Court, Thrissur" },
  { id: 12005, stateId: 12, name: "District Court, Kozhikode" },
  { id: 12006, stateId: 12, name: "District Court, Kannur" },
  { id: 12007, stateId: 12, name: "District Court, Kollam" },
  { id: 12008, stateId: 12, name: "District Court, Palakkad" },
  { id: 12009, stateId: 12, name: "District Court, Malappuram" },
  { id: 12010, stateId: 12, name: "District Court, Alappuzha" },
  { id: 12011, stateId: 12, name: "District Court, Kottayam" },
  { id: 12012, stateId: 12, name: "District Court, Idukki" },
  { id: 12013, stateId: 12, name: "District Court, Kasaragod" },
  { id: 12014, stateId: 12, name: "District Court, Pathanamthitta" },
  { id: 12015, stateId: 12, name: "District Court, Wayanad" },
  { id: 12016, stateId: 12, name: "Family Court, Ernakulam" },
  { id: 12017, stateId: 12, name: "Family Court, Thiruvananthapuram" },
  { id: 12018, stateId: 12, name: "Labour Court, Ernakulam" },
  { id: 12019, stateId: 12, name: "Consumer Disputes Redressal Commission, Kerala" },
  // Madhya Pradesh (13)
  { id: 13001, stateId: 13, name: "Madhya Pradesh High Court, Jabalpur" },
  { id: 13002, stateId: 13, name: "Indore Bench of MP High Court" },
  { id: 13003, stateId: 13, name: "Gwalior Bench of MP High Court" },
  { id: 13004, stateId: 13, name: "District Court, Bhopal" },
  { id: 13005, stateId: 13, name: "District Court, Indore" },
  { id: 13006, stateId: 13, name: "District Court, Jabalpur" },
  { id: 13007, stateId: 13, name: "District Court, Gwalior" },
  { id: 13008, stateId: 13, name: "Family Court, Bhopal" },
  { id: 13009, stateId: 13, name: "Consumer Disputes Redressal Commission, Madhya Pradesh" },
  // Maharashtra (14)
  { id: 14001, stateId: 14, name: "Bombay High Court" },
  { id: 14002, stateId: 14, name: "Nagpur Bench of Bombay High Court" },
  { id: 14003, stateId: 14, name: "Aurangabad Bench of Bombay High Court" },
  { id: 14004, stateId: 14, name: "City Civil Court, Mumbai" },
  { id: 14005, stateId: 14, name: "District Court, Pune" },
  { id: 14006, stateId: 14, name: "District Court, Nagpur" },
  { id: 14007, stateId: 14, name: "District Court, Thane" },
  { id: 14008, stateId: 14, name: "District Court, Aurangabad" },
  { id: 14009, stateId: 14, name: "District Court, Nashik" },
  { id: 14010, stateId: 14, name: "District Court, Kolhapur" },
  { id: 14011, stateId: 14, name: "Family Court, Mumbai" },
  { id: 14012, stateId: 14, name: "Labour Court, Mumbai" },
  { id: 14013, stateId: 14, name: "Consumer Disputes Redressal Commission, Maharashtra" },
  { id: 14014, stateId: 14, name: "Debt Recovery Tribunal, Mumbai" },
  { id: 14015, stateId: 14, name: "National Company Law Tribunal, Mumbai" },
  // Odisha (19)
  { id: 19001, stateId: 19, name: "Orissa High Court" },
  { id: 19002, stateId: 19, name: "District Court, Bhubaneswar" },
  { id: 19003, stateId: 19, name: "District Court, Cuttack" },
  { id: 19004, stateId: 19, name: "District Court, Rourkela" },
  { id: 19005, stateId: 19, name: "Family Court, Bhubaneswar" },
  { id: 19006, stateId: 19, name: "Consumer Disputes Redressal Commission, Odisha" },
  // Punjab (20)
  { id: 20001, stateId: 20, name: "Punjab & Haryana High Court" },
  { id: 20002, stateId: 20, name: "District Court, Ludhiana" },
  { id: 20003, stateId: 20, name: "District Court, Amritsar" },
  { id: 20004, stateId: 20, name: "District Court, Jalandhar" },
  { id: 20005, stateId: 20, name: "District Court, Patiala" },
  { id: 20006, stateId: 20, name: "Family Court, Chandigarh" },
  { id: 20007, stateId: 20, name: "Consumer Disputes Redressal Commission, Punjab" },
  // Rajasthan (21)
  { id: 21001, stateId: 21, name: "Rajasthan High Court, Jodhpur" },
  { id: 21002, stateId: 21, name: "Jaipur Bench of Rajasthan High Court" },
  { id: 21003, stateId: 21, name: "District Court, Jaipur" },
  { id: 21004, stateId: 21, name: "District Court, Jodhpur" },
  { id: 21005, stateId: 21, name: "District Court, Udaipur" },
  { id: 21006, stateId: 21, name: "District Court, Ajmer" },
  { id: 21007, stateId: 21, name: "District Court, Kota" },
  { id: 21008, stateId: 21, name: "Family Court, Jaipur" },
  { id: 21009, stateId: 21, name: "Consumer Disputes Redressal Commission, Rajasthan" },
  // Tamil Nadu (23)
  { id: 23001, stateId: 23, name: "Madras High Court" },
  { id: 23002, stateId: 23, name: "Madurai Bench of Madras High Court" },
  { id: 23003, stateId: 23, name: "City Civil Court, Chennai" },
  { id: 23004, stateId: 23, name: "District Court, Coimbatore" },
  { id: 23005, stateId: 23, name: "District Court, Madurai" },
  { id: 23006, stateId: 23, name: "District Court, Tiruchirappalli" },
  { id: 23007, stateId: 23, name: "District Court, Salem" },
  { id: 23008, stateId: 23, name: "District Court, Tirunelveli" },
  { id: 23009, stateId: 23, name: "District Court, Vellore" },
  { id: 23010, stateId: 23, name: "District Court, Erode" },
  { id: 23011, stateId: 23, name: "Family Court, Chennai" },
  { id: 23012, stateId: 23, name: "Labour Court, Chennai" },
  { id: 23013, stateId: 23, name: "Consumer Disputes Redressal Commission, Tamil Nadu" },
  // Telangana (24)
  { id: 24001, stateId: 24, name: "Telangana High Court" },
  { id: 24002, stateId: 24, name: "City Civil Court, Hyderabad" },
  { id: 24003, stateId: 24, name: "District Court, Warangal" },
  { id: 24004, stateId: 24, name: "District Court, Karimnagar" },
  { id: 24005, stateId: 24, name: "District Court, Nizamabad" },
  { id: 24006, stateId: 24, name: "Family Court, Hyderabad" },
  { id: 24007, stateId: 24, name: "Labour Court, Hyderabad" },
  { id: 24008, stateId: 24, name: "Consumer Disputes Redressal Commission, Telangana" },
  { id: 24009, stateId: 24, name: "National Company Law Tribunal, Hyderabad" },
  // Uttar Pradesh (26)
  { id: 26001, stateId: 26, name: "Allahabad High Court" },
  { id: 26002, stateId: 26, name: "Lucknow Bench of Allahabad High Court" },
  { id: 26003, stateId: 26, name: "District Court, Lucknow" },
  { id: 26004, stateId: 26, name: "District Court, Kanpur" },
  { id: 26005, stateId: 26, name: "District Court, Agra" },
  { id: 26006, stateId: 26, name: "District Court, Varanasi" },
  { id: 26007, stateId: 26, name: "District Court, Prayagraj" },
  { id: 26008, stateId: 26, name: "District Court, Meerut" },
  { id: 26009, stateId: 26, name: "District Court, Ghaziabad" },
  { id: 26010, stateId: 26, name: "Family Court, Lucknow" },
  { id: 26011, stateId: 26, name: "Labour Court, Lucknow" },
  { id: 26012, stateId: 26, name: "Consumer Disputes Redressal Commission, Uttar Pradesh" },
  { id: 26013, stateId: 26, name: "Debt Recovery Tribunal, Lucknow" },
  // Uttarakhand (27)
  { id: 27001, stateId: 27, name: "Uttarakhand High Court" },
  { id: 27002, stateId: 27, name: "District Court, Dehradun" },
  { id: 27003, stateId: 27, name: "District Court, Haridwar" },
  { id: 27004, stateId: 27, name: "District Court, Nainital" },
  { id: 27005, stateId: 27, name: "Family Court, Dehradun" },
  { id: 27006, stateId: 27, name: "Consumer Disputes Redressal Commission, Uttarakhand" },
  // West Bengal (28)
  { id: 28001, stateId: 28, name: "Calcutta High Court" },
  { id: 28002, stateId: 28, name: "Circuit Bench of Calcutta High Court, Port Blair" },
  { id: 28003, stateId: 28, name: "City Civil Court, Kolkata" },
  { id: 28004, stateId: 28, name: "District Court, Howrah" },
  { id: 28005, stateId: 28, name: "District Court, Asansol" },
  { id: 28006, stateId: 28, name: "District Court, Siliguri" },
  { id: 28007, stateId: 28, name: "District Court, Durgapur" },
  { id: 28008, stateId: 28, name: "Family Court, Kolkata" },
  { id: 28009, stateId: 28, name: "Labour Court, Kolkata" },
  { id: 28010, stateId: 28, name: "Consumer Disputes Redressal Commission, West Bengal" },
  { id: 28011, stateId: 28, name: "National Company Law Tribunal, Kolkata" },
  // Delhi (29)
  { id: 29001, stateId: 29, name: "Delhi High Court" },
  { id: 29002, stateId: 29, name: "District Court, Saket" },
  { id: 29003, stateId: 29, name: "District Court, Rohini" },
  { id: 29004, stateId: 29, name: "District Court, Tis Hazari" },
  { id: 29005, stateId: 29, name: "District Court, Patiala House" },
  { id: 29006, stateId: 29, name: "District Court, Karkardooma" },
  { id: 29007, stateId: 29, name: "District Court, Dwarka" },
  { id: 29008, stateId: 29, name: "Family Court, Delhi" },
  { id: 29009, stateId: 29, name: "Labour Court, Delhi" },
  { id: 29010, stateId: 29, name: "Consumer Disputes Redressal Commission, Delhi" },
  { id: 29011, stateId: 29, name: "National Company Law Tribunal, New Delhi" },
  { id: 29012, stateId: 29, name: "Debt Recovery Tribunal, New Delhi" },
  { id: 29013, stateId: 29, name: "Central Administrative Tribunal, New Delhi" },
  { id: 29014, stateId: 29, name: "Income Tax Appellate Tribunal, New Delhi" },
  // Jammu & Kashmir (30)
  { id: 30001, stateId: 30, name: "Jammu & Kashmir High Court" },
  { id: 30002, stateId: 30, name: "District Court, Srinagar" },
  { id: 30003, stateId: 30, name: "District Court, Jammu" },
  { id: 30004, stateId: 30, name: "Family Court, Srinagar" },
  { id: 30005, stateId: 30, name: "Consumer Disputes Redressal Commission, J&K" },
  // Puducherry (32)
  { id: 32001, stateId: 32, name: "Madras High Court (Puducherry Bench)" },
  { id: 32002, stateId: 32, name: "District Court, Puducherry" },
  { id: 32003, stateId: 32, name: "Family Court, Puducherry" },
  // Chandigarh (33)
  { id: 33001, stateId: 33, name: "Punjab & Haryana High Court" },
  { id: 33002, stateId: 33, name: "District Court, Chandigarh" },
  { id: 33003, stateId: 33, name: "Family Court, Chandigarh" },
  { id: 33004, stateId: 33, name: "Consumer Disputes Redressal Commission, Chandigarh" },
];

// ─── Districts ────────────────────────────────────────────────────────────────

export interface DistrictItem {
  id: number;
  value: string;
  name: string;
  stateId: number;
}

// Derived from the "District Court, <District>" entries above — keeps the
// district list in sync with the seeded courts without a separate master table.
// export const STATIC_DISTRICTS: DistrictItem[] = STATIC_COURTS
//   .filter((c) => c.name.startsWith("District Court, "))
//   .map((c) => ({ id: c.id, stateId: c.stateId, name: c.name.replace("District Court, ", "") }));

